### PR TITLE
P4 theme 

### PR DESCRIPTION
**Pull request by Dscano**
- Added P4 theme yaml file for pdf generator. ✅
- Added P4 theme css file for HTML generator. ✅

### CODE REVIEW

**Comment by jafingerhut** [comment]
Thanks for working on this!

A few quick comments from looking at the PDF generated after 7 commits on this PR:

When the line spacing between paragraphs is the same as the line spacing within a paragraph, indenting the first line of each paragraph looks a lot better to my eyes, the way the current Madoko PDF does.  Do you know if there is a setting to cause indentation of the first line of each paragraph?  Or perhaps instead, have something like half-a-line of vertical spacing between paragraphs?

Similarly, no extra white space before section headings seems a little too "tight" to me, as well as no vertical white space between figures and the text that follows.  I understand if there was too much before, but it seems to me there is too little now.

**Comment by Dscano** [comment]
Hi Andy,

I still need to explore that part. My to-do list is:

- TOC
- Text
- Lists
- Images
- Code
- HTTP version

In other words, I decided to do a PR to update you step by step.

**Comment by jafingerhut** [comment]
FYI, I would ask that we please keep all section headings up to 5 levels deep in the table of contents.  There are only a few ssection headings deeper than 3 levels, but I find it really annoying in the current Madoko output that I cannot find them by looking in the table of contents.

**Comment by Dscano** [comment]
> per than 3 levels, but I find it really annoying in the current Madoko output that I cannot find them by looking in the table of contents.

Sure, sorry Andy, my fault. I'm struggling with this TOC level.

**Comment by jafingerhut** [comment]
FYI, if your goal is to (nearly) exactly reproduce the Madoko PDF output, I hope you aren't spending lots of time on that.  I think the goal should be to make it look reasonably good :-)

**Comment by Dscano** [comment]
> FYI, if your goal is to (nearly) exactly reproduce the Madoko PDF output, I hope you aren't spending lots of time on that. I think the goal should be to make it look reasonably good :-)

True, but  I'll try to make it as good as I can

**Comment by Dscano** [comment]
Hi Andy, 

From my understanding, the code box coloring is performed by applying Rouge highlighter. So if we want to change some coloring within the box, we have to change the Rouge configuration. Does that make sense to you?

**Comment by jafingerhut** [comment]
@Dscano That is my belief, yes, but Ryan Goodfellow (who made the addition of P4 to the rouge library) might know otherwise. @rcgoodfellow

**Comment by rcgoodfellow** [comment]
I believe the aesthetics of what rouge does (e.g., choice of colors) should all be configurable through theming or other declarative configurations without having to change the lexical/parsing code I contributed to rouge.

**Comment by Dscano** [comment]
> I believe the aesthetics of what rouge does (e.g., choice of colors) should all be configurable through theming or other declarative configurations without having to change the lexical/parsing code I contributed to rouge.

Thank you for the answer. I'll conduct a further investigation

**Comment by jafingerhut** [comment]
@Dscano This commit shows some changes I made to the Makefile that demonstrate picking one of the named rouge color themes that comes as part of the rouge gem.  https://github.com/jafingerhut/learn-asciidoc/commit/85b7f7931cdbc630fa6af070043f8ba1749b21f6

I never tested this, but I would not be surprised if you can create your own color theme file (outside of the rouge gem), and use that, specified somehow on the command line.

**Comment by Dscano** [comment]
> @Dscano This commit shows some changes I made to the Makefile that demonstrate picking one of the named rouge color themes that comes as part of the rouge gem. [85b7f79](https://github.com/jafingerhut/learn-asciidoc/commit/85b7f7931cdbc630fa6af070043f8ba1749b21f6)
> 
> I never tested this, but I would not be surprised if you can create your own color theme file (outside of the rouge gem), and use that, specified somehow on the command line.

I posted a message on the Asciidoctor Zulip, and I received this answer. 
```
How can I change the color in code blocks?
What you are looking for is the syntax highlighter theme. You can find information about it
on the  following page in the docs: https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/highlightjs/#change-the-theme
```

So you are right, Andy. I'll try to make some changes in the next few days.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
